export const TEAMS_SQUADS = {
  MEX: [
    { name: "Guillermo Ochoa", club: "AVS Futebol" },
    { name: "Edson Álvarez", club: "West Ham" },
    { name: "Santiago Giménez", club: "Feyenoord" },
    { name: "Hirving Lozano", club: "San Diego FC" },
    { name: "Luis Chávez", club: "Dynamo Moscou" },
    { name: "Orbelín Pineda", club: "AEK Athènes" },
    { name: "César Montes", club: "Lokomotiv Moscou" },
    { name: "Johan Vásquez", club: "Genoa" },
    { name: "Jorge Sánchez", club: "Cruz Azul" },
    { name: "Henry Martín", club: "Club América" },
    { name: "Uriel Antuna", club: "Tigres UANL" }
  ],
  RSA: [
    { name: "Ronwen Williams", club: "Mamelodi Sundowns" },
    { name: "Percy Tau", club: "Al Ahly" },
    { name: "Teboho Mokoena", club: "Mamelodi Sundowns" },
    { name: "Themba Zwane", club: "Mamelodi Sundowns" },
    { name: "Aubrey Modiba", club: "Mamelodi Sundowns" },
    { name: "Mothobi Mvala", club: "Mamelodi Sundowns" },
    { name: "Khuliso Mudau", club: "Mamelodi Sundowns" },
    { name: "Sphephelo Sithole", club: "Gil Vicente" },
    { name: "Evidence Makgopa", club: "Orlando Pirates" },
    { name: "Thapelo Morena", club: "Mamelodi Sundowns" },
    { name: "Grant Kekana", club: "Mamelodi Sundowns" }
  ],
  KOR: [
    { name: "Son Heung-min", club: "Tottenham" },
    { name: "Kim Min-jae", club: "Bayern Munich" },
    { name: "Lee Kang-in", club: "PSG" },
    { name: "Hwang Hee-chan", club: "Wolverhampton" },
    { name: "Cho Gue-sung", club: "Midtjylland" },
    { name: "Lee Jae-sung", club: "Mainz 05" },
    { name: "Hwang In-beom", club: "Feyenoord" },
    { name: "Seol Young-woo", club: "Étoile Rouge de Belgrade" },
    { name: "Kim Young-gwon", club: "Ulsan HD" },
    { name: "Jo Hyeon-woo", club: "Ulsan HD" },
    { name: "Jeong Woo-yeong", club: "Union Berlin" }
  ],
  CZE: [
    { name: "Patrik Schick", club: "Bayer Leverkusen" },
    { name: "Tomáš Souček", club: "West Ham" },
    { name: "Vladimír Coufal", club: "West Ham" },
    { name: "Adam Hložek", club: "Hoffenheim" },
    { name: "Václav Černý", club: "Rangers" },
    { name: "Alex Král", club: "Espanyol Barcelone" },
    { name: "Ladislav Krejčí", club: "Girona" },
    { name: "Tomáš Holeš", club: "Slavia Prague" },
    { name: "David Douděra", club: "Slavia Prague" },
    { name: "Jindřich Staněk", club: "Slavia Prague" },
    { name: "Antonín Barák", club: "Kasımpaşa" }
  ],
  CAN: [
    { name: "Alphonso Davies", club: "Bayern Munich" },
    { name: "Jonathan David", club: "Lille" },
    { name: "Tajon Buchanan", club: "Inter Milan" },
    { name: "Cyle Larin", club: "Majorque" },
    { name: "Stephen Eustáquio", club: "FC Porto" },
    { name: "Ismaël Koné", club: "Marseille" },
    { name: "Alistair Johnston", club: "Celtic" },
    { name: "Kamal Miller", club: "Portland Timbers" },
    { name: "Maxime Crépeau", club: "Portland Timbers" },
    { name: "Richie Laryea", club: "Toronto FC" },
    { name: "Derek Cornelius", club: "Marseille" }
  ],
  BIH: [
    { name: "Edin Džeko", club: "Fenerbahçe" },
    { name: "Sead Kolašinac", club: "Atalanta" },
    { name: "Miralem Pjanić", club: "Al-Sharjah" },
    { name: "Amar Dedić", club: "RB Salzbourg" },
    { name: "Ermedin Demirović", club: "VfB Stuttgart" },
    { name: "Benjamin Tahirović", club: "Ajax" },
    { name: "Dennis Hadžikadunić", club: "Hambourg SV" },
    { name: "Jusuf Gazibegović", club: "Sturm Graz" },
    { name: "Rade Krunić", club: "Étoile Rouge de Belgrade" },
    { name: "Nikola Vasilj", club: "FC St. Pauli" },
    { name: "Anel Ahmedhodžić", club: "Sheffield United" }
  ],
  QAT: [
    { name: "Akram Afif", club: "Al-Sadd" },
    { name: "Almoez Ali", club: "Al-Duhail" },
    { name: "Boualem Khoukhi", club: "Al-Sadd" },
    { name: "Karim Boudiaf", club: "Al-Duhail" },
    { name: "Abdelkarim Hassan", club: "Al-Wakrah" },
    { name: "Saad Al-Sheeb", club: "Al-Sadd" },
    { name: "Bassam Al-Rawi", club: "Al-Duhail" },
    { name: "Pedro Miguel", club: "Al-Sadd" },
    { name: "Homam Ahmed", club: "Al-Gharafa" },
    { name: "Tarek Salman", club: "Al-Sadd" },
    { name: "Meshaal Barsham", club: "Al-Sadd" }
  ],
  SUI: [
    { name: "Granit Xhaka", club: "Bayer Leverkusen" },
    { name: "Yann Sommer", club: "Inter Milan" },
    { name: "Manuel Akanji", club: "Manchester City" },
    { name: "Breel Embolo", club: "Monaco" },
    { name: "Dan Ndoye", club: "Bologne" },
    { name: "Remo Freuler", club: "Bologne" },
    { name: "Denis Zakaria", club: "Monaco" },
    { name: "Ruben Vargas", club: "Augsburg" },
    { name: "Silvan Widmer", club: "Mayence 05" },
    { name: "Ricardo Rodríguez", club: "Betis Séville" },
    { name: "Gregor Kobel", club: "Borussia Dortmund" }
  ],
  BRA: [
    { name: "Vinícius Júnior", club: "Real Madrid" },
    { name: "Rodrygo Goes", club: "Real Madrid" },
    { name: "Raphinha", club: "Barcelone" },
    { name: "Gabriel Martinelli", club: "Arsenal" },
    { name: "Bruno Guimarães", club: "Newcastle" },
    { name: "Lucas Paquetá", club: "West Ham" },
    { name: "Casemiro", club: "Manchester United" },
    { name: "Marquinhos", club: "PSG" },
    { name: "Gabriel Magalhães", club: "Arsenal" },
    { name: "Danilo", club: "Juventus" },
    { name: "Alisson Becker", club: "Liverpool" }
  ],
  MAR: [
    { name: "Yassine Bounou", club: "Al-Hilal" },
    { name: "Munir El Kajoui", club: "RS Berkane" },
    { name: "Ahmed Tagnaouti", club: "AS FAR" },
    { name: "Achraf Hakimi", club: "PSG" },
    { name: "Noussair Mazraoui", club: "Manchester United" },
    { name: "Nayef Aguerd", club: "Olympique de Marseille" },
    { name: "Chadi Riad", club: "Crystal Palace" },
    { name: "Issa Diop", club: "Fulham" },
    { name: "Anass Salah-Eddine", club: "PSV Eindhoven" },
    { name: "Youssef Belammari", club: "Al Ahly" },
    { name: "Redouane Halhal", club: "KV Mechelen" },
    { name: "Zakaria El Ouahdi", club: "KRC Genk" },
    { name: "Sofyan Amrabat", club: "Real Betis" },
    { name: "Azzedine Ounahi", club: "Girona" },
    { name: "Bilal El Khannouss", club: "VfB Stuttgart" },
    { name: "Ismael Saibari", club: "PSV Eindhoven" },
    { name: "Ayyoub Bouaddi", club: "Lille OSC" },
    { name: "Neil El Aynaoui", club: "AS Roma" },
    { name: "Samir El Mourabet", club: "RC Strasbourg" },
    { name: "Yassine Gessime", club: "RC Strasbourg" },
    { name: "Brahim Díaz", club: "Real Madrid" },
    { name: "Ayoub El Kaabi", club: "Olympiacos" },
    { name: "Soufiane Rahimi", club: "Al Ain FC" },
    { name: "Abde Ezzalzouli", club: "Real Betis" },
    { name: "Chemsdine Talbi", club: "Sunderland" },
    { name: "Ayoub Amaimouni", club: "Eintracht Frankfurt" }
  ],
  HAI: [
    { name: "Duckens Nazon", club: "Kayserispor" },
    { name: "Frantzdy Pierrot", club: "AEK Athènes" },
    { name: "Derrick Etienne Jr.", club: "Toronto FC" },
    { name: "Carlens Arcus", club: "Angers SCO" },
    { name: "Garissone Innocent", club: "Eupen" },
    { name: "Ricardo Adé", club: "LDU Quito" },
    { name: "Danley Jean Jacques", club: "Portland Timbers" },
    { name: "Alex Christian", club: "AEL Limassol" },
    { name: "Bryan Alceus", club: "Doxa Katokopias" },
    { name: "Fafà Picault", club: "Vancouver Whitecaps" },
    { name: "Jean-Kévin Duverne", club: "Nantes" }
  ],
  SCO: [
    { name: "Andrew Robertson", club: "Liverpool" },
    { name: "John McGinn", club: "Aston Villa" },
    { name: "Scott McTominay", club: "Naples" },
    { name: "Billy Gilmour", club: "Naples" },
    { name: "Che Adams", club: "Torino" },
    { name: "Callum McGregor", club: "Celtic" },
    { name: "Kieran Tierney", club: "Arsenal" },
    { name: "Jack Hendry", club: "Al-Ettifaq" },
    { name: "Ryan Porteous", club: "Watford" },
    { name: "Angus Gunn", club: "Norwich City" },
    { name: "Lyndon Dykes", club: "Birmingham City" }
  ],
  USA: [
    { name: "Christian Pulisic", club: "AC Milan" },
    { name: "Weston McKennie", club: "Juventus" },
    { name: "Folarin Balogun", club: "Monaco" },
    { name: "Tyler Adams", club: "Bournemouth" },
    { name: "Gio Reyna", club: "Borussia Dortmund" },
    { name: "Timothy Weah", club: "Juventus" },
    { name: "Antonee Robinson", club: "Fulham" },
    { name: "Sergiño Dest", club: "PSV Eindhoven" },
    { name: "Chris Richards", club: "Crystal Palace" },
    { name: "Matt Turner", club: "Crystal Palace" },
    { name: "Yunus Musah", club: "AC Milan" }
  ],
  PAR: [
    { name: "Miguel Almirón", club: "Newcastle" },
    { name: "Julio Enciso", club: "Brighton" },
    { name: "Antonio Sanabria", club: "Torino" },
    { name: "Gustavo Gómez", club: "Palmeiras" },
    { name: "Mathías Villasanti", club: "Grêmio" },
    { name: "Júnior Alonso", club: "Atlético Mineiro" },
    { name: "Omar Alderete", club: "Getafe" },
    { name: "Matías Rojas", club: "Inter Miami" },
    { name: "Richard Sánchez", club: "Club América" },
    { name: "Carlos Coronel", club: "New York Red Bulls" },
    { name: "Ramón Sosa", club: "Nottingham Forest" }
  ],
  AUS: [
    { name: "Mathew Ryan", club: "AS Roma" },
    { name: "Harry Souttar", club: "Sheffield United" },
    { name: "Jackson Irvine", club: "FC St. Pauli" },
    { name: "Mitchell Duke", club: "Machida Zelvia" },
    { name: "Craig Goodwin", club: "Al-Wehda" },
    { name: "Connor Metcalfe", club: "FC St. Pauli" },
    { name: "Keanu Baccus", club: "Mansfield Town" },
    { name: "Aziz Behich", club: "Melbourne City" },
    { name: "Kye Rowles", club: "Hearts" },
    { name: "Martin Boyle", club: "Hibernian" },
    { name: "Jordan Bos", club: "Westerlo" }
  ],
  TUR: [
    { name: "Hakan Çalhanoğlu", club: "Inter Milan" },
    { name: "Arda Güler", club: "Real Madrid" },
    { name: "Kenan Yıldız", club: "Juventus" },
    { name: "Kerem Aktürkoğlu", club: "Benfica" },
    { name: "Barış Alper Yılmaz", club: "Galatasaray" },
    { name: "Salih Özcan", club: "Wolfsburg" },
    { name: "Orkun Kökçü", club: "Benfica" },
    { name: "Ferdi Kadıoğlu", club: "Brighton" },
    { name: "Abdülkerim Bardakcı", club: "Galatasaray" },
    { name: "Merih Demiral", club: "Al-Ahli" },
    { name: "Uğurcan Çakır", club: "Trabzonspor" }
  ],
  GER: [
    { name: "Florian Wirtz", club: "Bayer Leverkusen" },
    { name: "Jamal Musiala", club: "Bayern Munich" },
    { name: "Kai Havertz", club: "Arsenal" },
    { name: "Joshua Kimmich", club: "Bayern Munich" },
    { name: "Antonio Rüdiger", club: "Real Madrid" },
    { name: "Jonathan Tah", club: "Bayer Leverkusen" },
    { name: "David Raum", club: "RB Leipzig" },
    { name: "Marc-André ter Stegen", club: "Barcelone" },
    { name: "Nico Schlotterbeck", club: "Borussia Dortmund" },
    { name: "Robert Andrich", club: "Bayer Leverkusen" },
    { name: "Niclas Füllkrug", club: "West Ham" }
  ],
  CUW: [
    { name: "Leandro Bacuna", club: "Groningen" },
    { name: "Juninho Bacuna", club: "Al-Wahda" },
    { name: "Kenji Gorré", club: "Umm Salal" },
    { name: "Vurnon Anita", club: "Sans club" },
    { name: "Rangelo Janga", club: "Eindhoven" },
    { name: "Eloy Room", club: "Vitesse" },
    { name: "Cuco Martina", club: "Sans club" },
    { name: "Brandley Kuwas", club: "Volendam" },
    { name: "Gervane Kastaneer", club: "Roda JC" },
    { name: "Sherel Floranus", club: "PEC Zwolle" },
    { name: "Juriën Gaari", club: "RKC Waalwijk" }
  ],
  CIV: [
    { name: "Sébastien Haller", club: "Leganés" },
    { name: "Simon Adingra", club: "Brighton" },
    { name: "Franck Kessié", club: "Al-Ahli" },
    { name: "Seko Fofana", club: "Al-Ettifaq" },
    { name: "Ibrahim Sangaré", club: "Nottingham Forest" },
    { name: "Oumar Diakité", club: "Reims" },
    { name: "Evan Ndicka", club: "AS Roma" },
    { name: "Odilon Kossounou", club: "Atalanta" },
    { name: "Wilfried Singo", club: "Monaco" },
    { name: "Yahia Fofana", club: "Angers SCO" },
    { name: "Serge Aurier", club: "Sans club" }
  ],
  ECU: [
    { name: "Enner Valencia", club: "Internacional" },
    { name: "Moisés Caicedo", club: "Chelsea" },
    { name: "Piero Hincapié", club: "Bayer Leverkusen" },
    { name: "Willian Pacho", club: "PSG" },
    { name: "Pervis Estupiñán", club: "Brighton" },
    { name: "Kendry Páez", club: "Independiente del Valle" },
    { name: "Angelo Preciado", club: "Sparta Prague" },
    { name: "Félix Torres", club: "Corinthians" },
    { name: "Carlos Gruezo", club: "San Jose Earthquakes" },
    { name: "Alexander Domínguez", club: "LDU Quito" },
    { name: "Jeremy Sarmiento", club: "Burnley" }
  ],
  NED: [
    { name: "Memphis Depay", club: "Corinthians" },
    { name: "Cody Gakpo", club: "Liverpool" },
    { name: "Xavi Simons", club: "RB Leipzig" },
    { name: "Frenkie de Jong", club: "Barcelone" },
    { name: "Tijjani Reijnders", club: "AC Milan" },
    { name: "Jerdy Schouten", club: "PSV Eindhoven" },
    { name: "Virgil van Dijk", club: "Liverpool" },
    { name: "Nathan Aké", club: "Manchester City" },
    { name: "Denzel Dumfries", club: "Inter Milan" },
    { name: "Bart Verbruggen", club: "Brighton" },
    { name: "Matthijs de Ligt", club: "Manchester United" }
  ],
  JPN: [
    { name: "Kaoru Mitoma", club: "Brighton" },
    { name: "Wataru Endo", club: "Liverpool" },
    { name: "Takefusa Kubo", club: "Real Sociedad" },
    { name: "Ritsu Doan", club: "Fribourg" },
    { name: "Ayase Ueda", club: "Feyenoord" },
    { name: "Takumi Minamino", club: "Monaco" },
    { name: "Hidemasa Morita", club: "Sporting CP" },
    { name: "Hiroki Ito", club: "Bayern Munich" },
    { name: "Ko Itakura", club: "Borussia M'gladbach" },
    { name: "Zion Suzuki", club: "Parme" },
    { name: "Yukinari Sugawara", club: "Southampton" }
  ],
  SWE: [
    { name: "Alexander Isak", club: "Newcastle" },
    { name: "Viktor Gyökeres", club: "Sporting CP" },
    { name: "Dejan Kulusevski", club: "Tottenham" },
    { name: "Emil Forsberg", club: "New York Red Bulls" },
    { name: "Jens Cajuste", club: "Ipswich Town" },
    { name: "Hugo Larsson", club: "Eintracht Francfort" },
    { name: "Victor Lindelöf", club: "Manchester United" },
    { name: "Isak Hien", club: "Atalanta" },
    { name: "Ludwig Augustinsson", club: "Anderlecht" },
    { name: "Robin Olsen", club: "Aston Villa" },
    { name: "Emil Holm", club: "Bologne" }
  ],
  TUN: [
    { name: "Youssef Msakni", club: "Al-Arabi" },
    { name: "Elias Achouri", club: "FC Copenhague" },
    { name: "Ellyes Skhiri", club: "Eintracht Francfort" },
    { name: "Aïssa Laïdouni", club: "Al-Wakrah" },
    { name: "Wajdi Kechrida", club: "Gharafa" },
    { name: "Montassar Talbi", club: "Lorient" },
    { name: "Yassine Meriah", club: "Espérance de Tunis" },
    { name: "Ali Abdi", club: "Nice" },
    { name: "Mouez Hassen", club: "Club Africain" },
    { name: "Hamza Rafia", club: "Lecce" },
    { name: "Anis Ben Slimane", club: "Norwich City" }
  ],
  BEL: [
    { name: "Kevin De Bruyne", club: "Manchester City" },
    { name: "Romelu Lukaku", club: "Naples" },
    { name: "Jérémy Doku", club: "Manchester City" },
    { name: "Leandro Trossard", club: "Arsenal" },
    { name: "Amadou Onana", club: "Aston Villa" },
    { name: "Youri Tielemans", club: "Aston Villa" },
    { name: "Wout Faes", club: "Leicester" },
    { name: "Zeno Debast", club: "Sporting CP" },
    { name: "Timothy Castagne", club: "Fulham" },
    { name: "Koen Casteels", club: "Al-Qadsiah" },
    { name: "Johan Bakayoko", club: "PSV Eindhoven" }
  ],
  EGY: [
    { name: "Mohamed Salah", club: "Liverpool" },
    { name: "Mostafa Mohamed", club: "Nantes" },
    { name: "Trezeguet", club: "Al-Rayyan" },
    { name: "Omar Marmoush", club: "Eintracht Francfort" },
    { name: "Mohamed Elneny", club: "Al-Jazira" },
    { name: "Marwan Attia", club: "Al Ahly" },
    { name: "Emam Ashour", club: "Al Ahly" },
    { name: "Mohamed Abdelmonem", club: "Nice" },
    { name: "Ahmed Hegazi", club: "Neom SC" },
    { name: "Mohamed El Shenawy", club: "Al Ahly" },
    { name: "Mohamed Hany", club: "Al Ahly" }
  ],
  IRN: [
    { name: "Mehdi Taremi", club: "Inter Milan" },
    { name: "Sardar Azmoun", club: "Shabab Al-Ahli" },
    { name: "Alireza Jahanbakhsh", club: "Heerenveen" },
    { name: "Saman Ghoddos", club: "Ittihad Kalba" },
    { name: "Saeid Ezatolahi", club: "Shabab Al-Ahli" },
    { name: "Mehdi Torabi", club: "Tractor" },
    { name: "Milad Mohammadi", club: "Persépolis" },
    { name: "Shojae Khalilzadeh", club: "Tractor" },
    { name: "Hossein Kanaanizadegan", club: "Persépolis" },
    { name: "Alireza Beiranvand", club: "Tractor" },
    { name: "Ramin Rezaeian", club: "Esteghlal" }
  ],
  NZL: [
    { name: "Chris Wood", club: "Nottingham Forest" },
    { name: "Liberato Cacace", club: "Empoli" },
    { name: "Marko Stamenic", club: "Olympiacos" },
    { name: "Matthew Garbett", club: "NAC Breda" },
    { name: "Sarpreet Singh", club: "UD Leiria" },
    { name: "Tyler Bindon", club: "Reading" },
    { name: "Michael Boxall", club: "Minnesota United" },
    { name: "Nando Pijnaker", club: "Sligo Rovers" },
    { name: "Tommy Smith", club: "Auckland FC" },
    { name: "Oliver Sail", club: "Perth Glory" },
    { name: "Callum McCowatt", club: "Silkeborg" }
  ],
  ESP: [
    { name: "Lamine Yamal", club: "Barcelone" },
    { name: "Nico Williams", club: "Athletic Bilbao" },
    { name: "Dani Olmo", club: "Barcelone" },
    { name: "Álvaro Morata", club: "AC Milan" },
    { name: "Rodri Hernández", club: "Manchester City" },
    { name: "Fabián Ruiz", club: "PSG" },
    { name: "Pedri González", club: "Barcelone" },
    { name: "Dani Carvajal", club: "Real Madrid" },
    { name: "Robin Le Normand", club: "Atlético Madrid" },
    { name: "Aymeric Laporte", club: "Al-Nassr" },
    { name: "Unai Simón", club: "Athletic Bilbao" }
  ],
  CPV: [
    { name: "Ryan Mendes", club: "Karagümrük" },
    { name: "Garry Rodrigues", club: "Sivasspor" },
    { name: "Jovane Cabral", club: "Estrela Amadora" },
    { name: "Jamiro Monteiro", club: "PEC Zwolle" },
    { name: "Kenny Rocha Santos", club: "AEZ Zakakiou" },
    { name: "Deroy Duarte", club: "Ludogorets" },
    { name: "Logan Costa", club: "Villarreal" },
    { name: "Roberto Lopes", club: "Shamrock Rovers" },
    { name: "Vozinha", club: "AS Trenčín" },
    { name: "Steven Moreira", club: "Columbus Crew" },
    { name: "Patrick Andrade", club: "Qarabag" }
  ],
  KSA: [
    { name: "Salem Al-Dawsari", club: "Al-Hilal" },
    { name: "Firas Al-Buraikan", club: "Al-Ahli" },
    { name: "Saleh Al-Shehri", club: "Al-Ittihad" },
    { name: "Mohamed Kanno", club: "Al-Hilal" },
    { name: "Abdulelah Al-Malki", club: "Al-Ettifaq" },
    { name: "Musab Al-Juwayr", club: "Al-Shabab" },
    { name: "Yasser Al-Shahrani", club: "Al-Hilal" },
    { name: "Ali Al-Bulaihi", club: "Al-Hilal" },
    { name: "Saud Abdulhamid", club: "AS Roma" },
    { name: "Mohammed Al-Owais", club: "Al-Hilal" },
    { name: "Sultan Al-Ghannam", club: "Al-Nassr" }
  ],
  URU: [
    { name: "Luis Suárez", club: "Inter Miami" },
    { name: "Darwin Núñez", club: "Liverpool" },
    { name: "Federico Valverde", club: "Real Madrid" },
    { name: "Rodrigo Bentancur", club: "Tottenham" },
    { name: "Manuel Ugarte", club: "Manchester United" },
    { name: "Nicolás de la Cruz", club: "Flamengo" },
    { name: "Ronald Araújo", club: "Barcelone" },
    { name: "José María Giménez", club: "Atlético Madrid" },
    { name: "Mathías Olivera", club: "Naples" },
    { name: "Sergio Rochet", club: "Internacional" },
    { name: "Facundo Pellistri", club: "Panathinaikos" }
  ],
  FRA: [
    { name: "Kylian Mbappé", club: "Real Madrid" },
    { name: "Antoine Griezmann", club: "Atlético Madrid" },
    { name: "Ousmane Dembélé", club: "PSG" },
    { name: "Marcus Thuram", club: "Inter Milan" },
    { name: "Eduardo Camavinga", club: "Real Madrid" },
    { name: "Aurélien Tchouaméni", club: "Real Madrid" },
    { name: "N'Golo Kanté", club: "Al-Ittihad" },
    { name: "William Saliba", club: "Arsenal" },
    { name: "Dayot Upamecano", club: "Bayern Munich" },
    { name: "Theo Hernandez", club: "AC Milan" },
    { name: "Mike Maignan", club: "AC Milan" }
  ],
  SEN: [
    { name: "Sadio Mané", club: "Al-Nassr" },
    { name: "Nicolas Jackson", club: "Chelsea" },
    { name: "Ismaïla Sarr", club: "Crystal Palace" },
    { name: "Iliman Ndiaye", club: "Everton" },
    { name: "Lamine Camara", club: "Monaco" },
    { name: "Pape Matar Sarr", club: "Tottenham" },
    { name: "Idrissa Gueye", club: "Everton" },
    { name: "Kalidou Koulibaly", club: "Al-Hilal" },
    { name: "Abdou Diallo", club: "Al-Arabi" },
    { name: "Edouard Mendy", club: "Al-Ahli" },
    { name: "Moussa Niakhaté", club: "Lyon" }
  ],
  IRQ: [
    { name: "Aymen Hussein", club: "Al-Khor" },
    { name: "Ali Jasim", club: "Côme 1907" },
    { name: "Mohanad Ali", club: "Al-Shorta" },
    { name: "Ibrahim Bayesh", club: "Al-Riyadh" },
    { name: "Youssef Amyn", club: "Al-Wehda" },
    { name: "Amir Al-Ammari", club: "Cracovia" },
    { name: "Osama Rashid", club: "Erbil SC" },
    { name: "Rebin Sulaka", club: "FC Seoul" },
    { name: "Saad Natiq", club: "Al-Talaba" },
    { name: "Jalal Hassan", club: "Al-Zawraa" },
    { name: "Hussein Ali", club: "Heerenveen" }
  ],
  NOR: [
    { name: "Erling Haaland", club: "Manchester City" },
    { name: "Martin Ødegaard", club: "Arsenal" },
    { name: "Alexander Sørloth", club: "Atlético Madrid" },
    { name: "Antonio Nusa", club: "RB Leipzig" },
    { name: "Sander Berge", club: "Fulham" },
    { name: "Patrick Berg", club: "Bodø/Glimt" },
    { name: "Julian Ryerson", club: "Borussia Dortmund" },
    { name: "Leo Østigård", club: "Rennes" },
    { name: "Andreas Hanche-Olsen", club: "Mayence 05" },
    { name: "Ørjan Nyland", club: "Séville" },
    { name: "Kristoffer Ajer", club: "Brentford" }
  ],
  PRT: [
    { name: "Cristiano Ronaldo", club: "Al-Nassr" },
    { name: "Rafael Leão", club: "AC Milan" },
    { name: "Bruno Fernandes", club: "Manchester United" },
    { name: "Bernardo Silva", club: "Manchester City" },
    { name: "Vitinha", club: "PSG" },
    { name: "João Palhinha", club: "Bayern Munich" },
    { name: "Rúben Dias", club: "Manchester City" },
    { name: "Diogo Jota", club: "Liverpool" },
    { name: "João Cancelo", club: "Al-Hilal" },
    { name: "Diogo Costa", club: "FC Porto" },
    { name: "Nuno Mendes", club: "PSG" }
  ],
  COD: [
    { name: "Yoane Wissa", club: "Brentford" },
    { name: "Meschack Elia", club: "Young Boys" },
    { name: "Samuel Moutoussamy", club: "Sivasspor" },
    { name: "Charles Pickel", club: "Cremonese" },
    { name: "Theo Bongonda", club: "Spartak Moscou" },
    { name: "Chancel Mbemba", club: "Marseille" },
    { name: "Dylan Batubinsika", club: "Saint-Étienne" },
    { name: "Arthur Masuaku", club: "Besiktas" },
    { name: "Lionel Mpasi", club: "Rodez" },
    { name: "Gédéon Kalulu", club: "Lorient" },
    { name: "Simon Banza", club: "Trabzonspor" }
  ],
  UZB: [
    { name: "Eldor Shomurodov", club: "AS Roma" },
    { name: "Abbosbek Fayzullaev", club: "CSKA Moscou" },
    { name: "Jaloliddin Masharipov", club: "Esteghlal" },
    { name: "Otabek Shukurov", club: "Al-Fayha" },
    { name: "Odiljon Hamrobekov", club: "Al-Wahda" },
    { name: "Sherzod Nasrullaev", club: "Nasaf" },
    { name: "Rustam Ashurmatov", club: "Rubin Kazan" },
    { name: "Abdukodir Khusanov", club: "Lens" },
    { name: "Husniddin Aliqulov", club: "Çaykur Rizespor" },
    { name: "Utkir Yusupov", club: "Foolad" },
    { name: "Khojiakbar Alijonov", club: "Pakhtakor" }
  ],
  COL: [
    { name: "Luis Díaz", club: "Liverpool" },
    { name: "James Rodríguez", club: "Rayo Vallecano" },
    { name: "Jhon Durán", club: "Aston Villa" },
    { name: "Jhon Arias", club: "Fluminense" },
    { name: "Richard Ríos", club: "Palmeiras" },
    { name: "Jefferson Lerma", club: "Crystal Palace" },
    { name: "Daniel Muñoz", club: "Crystal Palace" },
    { name: "Davinson Sánchez", club: "Galatasaray" },
    { name: "Carlos Cuesta", club: "KRC Genk" },
    { name: "Camilo Vargas", club: "Atlas FC" },
    { name: "Johan Mojica", club: "Majorque" }
  ],
  ARG: [
    { name: "Lionel Messi", club: "Inter Miami" },
    { name: "Lautaro Martínez", club: "Inter Milan" },
    { name: "Julián Álvarez", club: "Atlético Madrid" },
    { name: "Alexis Mac Allister", club: "Liverpool" },
    { name: "Enzo Fernández", club: "Chelsea" },
    { name: "Rodrigo De Paul", club: "Atlético Madrid" },
    { name: "Cristian Romero", club: "Tottenham" },
    { name: "Lisandro Martínez", club: "Manchester United" },
    { name: "Nahuel Molina", club: "Atlético Madrid" },
    { name: "Emiliano Martínez", club: "Aston Villa" },
    { name: "Nicolás Tagliafico", club: "Lyon" }
  ],
  DZA: [
    { name: "Riyad Mahrez", club: "Al-Ahli" },
    { name: "Baghdad Bounedjah", club: "Al-Shamal" },
    { name: "Amine Gouiri", club: "Rennes" },
    { name: "Rayan Aït-Nouri", club: "Wolverhampton" },
    { name: "Houssem Aouar", club: "Al-Ittihad" },
    { name: "Ismaël Bennacer", club: "AC Milan" },
    { name: "Ramiz Zerrouki", club: "Feyenoord" },
    { name: "Ramy Bensebaini", club: "Borussia Dortmund" },
    { name: "Aïssa Mandi", club: "Lille" },
    { name: "Anthony Mandrea", club: "Caen" },
    { name: "Youcef Atal", club: "Al-Sadd" }
  ],
  AUT: [
    { name: "Marcel Sabitzer", club: "Borussia Dortmund" },
    { name: "Marko Arnautović", club: "Inter Milan" },
    { name: "Christoph Baumgartner", club: "RB Leipzig" },
    { name: "Konrad Laimer", club: "Bayern Munich" },
    { name: "Nicolas Seiwald", club: "RB Leipzig" },
    { name: "Florian Grillitsch", club: "Hoffenheim" },
    { name: "Stefan Posch", club: "Bologne" },
    { name: "Kevin Danso", club: "Lens" },
    { name: "Philipp Lienhart", club: "Fribourg" },
    { name: "Patrick Pentz", club: "Brøndby" },
    { name: "Alexander Prass", club: "Hoffenheim" }
  ],
  JOR: [
    { name: "Mousa Al-Tamari", club: "Montpellier" },
    { name: "Yazan Al-Naimat", club: "Al-Ahli" },
    { name: "Ali Olwan", club: "Selangor" },
    { name: "Nizar Al-Rashdan", club: "Al-Khaldiya" },
    { name: "Noor Al-Rawabdeh", club: "Selangor" },
    { name: "Mahmoud Al-Mardi", club: "Al-Hussein" },
    { name: "Salem Al-Ajalin", club: "Al-Faisaly" },
    { name: "Yazan Al-Arab", club: "FC Seoul" },
    { name: "Abdallah Nasib", club: "Al-Hussein" },
    { name: "Yazid Abu Layla", club: "Al-Jabalain" },
    { name: "Ihsan Haddad", club: "Al-Hussein" }
  ],
  ENG: [
    { name: "Harry Kane", club: "Bayern Munich" },
    { name: "Jude Bellingham", club: "Real Madrid" },
    { name: "Bukayo Saka", club: "Arsenal" },
    { name: "Phil Foden", club: "Manchester City" },
    { name: "Declan Rice", club: "Arsenal" },
    { name: "Cole Palmer", club: "Chelsea" },
    { name: "John Stones", club: "Manchester City" },
    { name: "Marc Guéhi", club: "Crystal Palace" },
    { name: "Kyle Walker", club: "Manchester City" },
    { name: "Jordan Pickford", club: "Everton" },
    { name: "Kieran Trippier", club: "Newcastle" }
  ],
  CRO: [
    { name: "Luka Modrić", club: "Real Madrid" },
    { name: "Andrej Kramarić", club: "Hoffenheim" },
    { name: "Mateo Kovačić", club: "Manchester City" },
    { name: "Mario Pašalić", club: "Atalanta" },
    { name: "Lovro Majer", club: "Wolfsburg" },
    { name: "Joško Gvardiol", club: "Manchester City" },
    { name: "Josip Šutalo", club: "Ajax" },
    { name: "Josip Stanišić", club: "Bayern Munich" },
    { name: "Dominik Livaković", club: "Fenerbahçe" },
    { name: "Ivan Perišić", club: "PSV Eindhoven" },
    { name: "Luka Sučić", club: "Real Sociedad" }
  ],
  GHA: [
    { name: "Mohammed Kudus", club: "West Ham" },
    { name: "Jordan Ayew", club: "Leicester" },
    { name: "Iñaki Williams", club: "Athletic Bilbao" },
    { name: "Antoine Semenyo", club: "Bournemouth" },
    { name: "Thomas Partey", club: "Arsenal" },
    { name: "Salis Abdul Samed", club: "Sunderland" },
    { name: "Alexander Djiku", club: "Fenerbahçe" },
    { name: "Mohammed Salisu", club: "Monaco" },
    { name: "Alidu Seidu", club: "Rennes" },
    { name: "Lawrence Ati-Zigi", club: "Saint-Gall" },
    { name: "Tariq Lamptey", club: "Brighton" }
  ],
  PAN: [
    { name: "Adalberto Carrasquilla", club: "Houston Dynamo" },
    { name: "Ismael Díaz", club: "Universidad Católica" },
    { name: "José Fajardo", club: "Universidad Católica" },
    { name: "Yoel Bárcenas", club: "Mazatlán" },
    { name: "Aníbal Godoy", club: "Nashville SC" },
    { name: "Cristian Martínez", club: "Ironi Kiryat Shmona" },
    { name: "Eric Davis", club: "Kosice" },
    { name: "José Córdoba", club: "Norwich City" },
    { name: "Andrés Andrade", club: "LASK" },
    { name: "Orlando Mosquera", club: "Al-Fayha" },
    { name: "Michael Amir Murillo", club: "Marseille" }
  ]
};
